name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust branch as per your setup

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      OPENSHIFT_SERVER_URL: ${{ secrets.OPENSHIFT_SERVER_URL }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust Node.js version as needed
      
      - name: Install dependencies
        run: npm install
      
      - name: Build and deploy to OpenShift
        run: |
          npm run build  # Adjust build command as per your project setup
          oc login $OPENSHIFT_SERVER_URL --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify
          oc project youtube-hossni  # Replace with your project namespace
          oc new-app ~/new-project/  # Replace with your Docker image path
          oc expose svc/youtube-hossni --port=3000  # Expose service on port 3000
